### ISSUE TITLE
Missing Patch in Boundary

### ISSUE THREAD

**Issue by lynetcha** [duxingyi-charles/Boundary_Sampled_Halfspaces#10]
I am trying to extract a BSH boundary but the resulting boundary has holes in it. Any idea what the cause of this issue is? I included screenshots of the input and results. And attached the input data.
![Screen Shot 2022-02-06 at 1 24 58 PM](https://user-images.githubusercontent.com/11138935/152702389-c17d54a2-946c-489f-814f-7ecb55df8a00.png)
<img width="652" alt="Screen Shot 2022-02-06 at 1 29 57 PM" src="https://user-images.githubusercontent.com/11138935/152702390-c920ee18-b1d6-4aa5-b2c4-0a0309cc2036.png">
<img width="640" alt="Screen Shot 2022-02-06 at 1 30 13 PM" src="https://user-images.githubusercontent.com/11138935/152702392-41923446-5b8f-45ec-ac06-68fdd58c6365.png">
[halfspace_repr_gt.zip](https://github.com/duxingyi-charles/Boundary_Sampled_Halfspaces/files/8011291/halfspace_repr_gt.zip)

**Comment by duxingyi-charles** [comment]
Thanks for your feedback. 
I found two issues in the input data.
1. implicit 9 and 10 are identical, which will cause problems for mesh arrangement. I have deleted implicit 10 in config.json and merged 10_sample.xyz into 9_sample.xyz.
2. implicit 3 has the wrong orientation (its normal points towards the interior of the 3D model). I have reversed the normal direction.

After the fix, the result looks good:
<img width="130" alt="image" src="https://user-images.githubusercontent.com/8947527/156616913-de52c152-5500-4c09-85f5-71a6a77ef21c.png">
<img width="162" alt="image" src="https://user-images.githubusercontent.com/8947527/156616964-e4b89922-fa9b-406e-b0a7-b16c87750d48.png">

For your information, here is the modified input and my result.
[halfspace_repr_gt_Charles.zip](https://github.com/duxingyi-charles/Boundary_Sampled_Halfspaces/files/8179692/halfspace_repr_gt_Charles.zip)

**Comment by lynetcha** [comment]
Thank you!
